### ISSUE TITLE
Add Config option to disable registration

### ISSUE THREAD

**Issue by enthus1ast** [bolt/users#13]
Currently the registration cannot be disabled (it seems).
Please add an option to the config that this can be disabled.

**Comment by I-Valchev** [comment]
What do you mean disable the registration?

If it's about the `/register` endpoint, you should be able to override the route in `routes.yaml` and then it won't be reachable.

**Comment by enthus1ast** [comment]
yes its about the register endpoint. 
I still think it would be good to just disable this in the plugins config.
Since it its a plugin feature, that must be disabled in the global routes config.


I've added this to my routes.yml:
```yaml
# ------------------------------------------------------------------------------
# Place your own routes here, that have a HIGHER priority than the default routes.

# Disable the registration added by bolt/users
foo:
  path: /register
  methods: []
  defaults:
    _controller: Bolt\Controller\Frontend\DetailController::renderTemplate
    template: 404.twig

# ------------------------------------------------------------------------------
```
